server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/store/api/v1/products/**